apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-web
  # namespace: $NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      name: cassandra-web
      labels:
        name: cassandra-web
        app: cassandra-web
    spec:
      nodeSelector:
        beta.kubernetes.io/instance-type: s-2vcpu-4gb
      containers:
        - name: cassandra-web$TIMESTAMP
          image: delermando/docker-cassandra-web:v0.4.0
          env:
            - name: CASSANDRA_HOST_IP
              value: '10.245.244.135'
          ports:
            - containerPort: 3000
