apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web
  # namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-web
  template:
    metadata:
      name: cassandra-web
      labels:
        app: cassandra-web
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: standard
      containers:
        - name: cassandra-web$TIMESTAMP
          image: delermando/docker-cassandra-web:v0.4.0
          env:
            - name: CASSANDRA_HOST_IP
              value: '10.244.0.94' # scylla-0 pod
          ports:
            - containerPort: 3000
