apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-hq
  namespace: $NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-hq
  template:
    metadata:
      name: elasticsearch-hq
      labels:
        app: elasticsearch-hq
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: standard
      containers:
        - name: elasticsearch-hq$TIMESTAMP
          image: elastichq/elasticsearch-hq
          env:
            - name: HQ_DEFAULT_URL
              value: 'http://10.244.78.2:9200'
          ports:
            - containerPort: 5000
