apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: irs-990-server
  annotations:
    # fake it by indicating this is provisioned dynamically, so the system
    # works properly
    pv.kubernetes.io/provisioned-by: dobs.csi.digitalocean.com
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage
  csi:
    driver: dobs.csi.digitalocean.com
    fsType: ext4
    volumeHandle: 756e4e82-963b-11ea-969f-0a58ac144db2
    volumeAttributes:
      com.digitalocean.csi/noformat: "true"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irs-990-server-claim
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: irs-990-server
  namespace: $NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      name: irs-990-server
      labels:
        name: irs-990-server
        app: irs-990-server
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: tech-by
      containers:
        - name: irs-990-server$TIMESTAMP
          image: halverneus/static-file-server
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: irs-990-server
            mountPath: /web
      volumes:
        - name: irs-990-server
          persistentVolumeClaim:
            claimName: irs-990-server-claim
