apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
  namespace: $NAMESPACE
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      name: load-balancer
      labels:
        app: load-balancer
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: standard
      containers:
        - name: load-balancer$TIMESTAMP
          image: registry.digitalocean.com/tech-by/load-balancer:$TAG
          # resources:
          #   requests:
          #     cpu: '$LOAD_BALANCER_CPU_REQUEST'
          env:
            - name: ADMIN_PASSWORD
              value: '$HAPROXY_ADMIN_PASS'
          ports:
            - containerPort: 80
