apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-pub-sub
  namespace: $NAMESPACE
spec:
  serviceName: redis-pub-sub
  replicas: 1
  selector:
    matchLabels:
      app: redis-pub-sub
  template:
    metadata:
      labels:
        app: redis-pub-sub
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: standard
      containers:
        - name: redis$TIMESTAMP
          image: redis:6.0.6
          resources:
            # requests:
            #   memory: '$REDIS_PUB_SUB_MEMORY_REQUEST'
            # limits:
            #   cpu: '$REDIS_PUB_SUB_MAX_CPU'
            #   memory: '$REDIS_PUB_SUB_MAX_MEMORY'
          args:
            - --maxmemory
            - '$REDIS_PUB_SUB_MAX_MEMORY'
            - --maxmemory-policy
            - allkeys-lru
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 50Gi
