apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage-xfs
provisioner: dobs.csi.digitalocean.com
parameters:
  fsType: xfs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: scylla
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      app: scylla
  serviceName: scylla
  replicas: 1 # 4
  template:
    metadata:
      labels:
        app: scylla
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: standard
      containers:
      - name: scylla
        image: scylladb/scylla:3.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        - containerPort: 9180
          name: prometheus
        # resources:
        #   limits:
        #     cpu: $SCYLLA_CPU_LIMIT
            # memory: 1Gi
          # requests:
          #  cpu: "500m"
          #  memory: 1Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        # lifecycle:
        #   preStop:
        #     exec:
        #       command: ["/bin/sh", "-c", "PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
        args:
          - --seeds
          - scylla-0.scylla.$NAMESPACE.svc.cluster.local
          - --memory
          - '$SCYLLA_MEMORY_LIMIT'
          - --developer-mode
          - '0'
          # - --smp
          # - '$SCYLLA_SMP'
          - --experimental
          - '0'

        env:
        #   - name: MAX_HEAP_SIZE
        #     value: 512M
        #   - name: HEAP_NEWSIZE
        #     value: 100M
        #   - name: CASSANDRA_SEEDS
        #     value: "scylla-0.scylla.$NAMESPACE.svc.cluster.local"
          - name: CLUSTER_NAME
            value: "techby-main"
        #   - name: CASSANDRA_DC
        #     value: "DC1"
        #   - name: CASSANDRA_RACK
        #     value: "Rack1"
        #   - name: CASSANDRA_AUTO_BOOTSTRAP
        #     value: "false"
        #   - name: POD_IP
        #     valueFrom:
        #       fieldRef:
        #         fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            # - /bin/bash
            # - -c
            # - /ready-probe.sh
            - nodetool
            - status
          initialDelaySeconds: 90
          timeoutSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/scylla
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: do-block-storage-xfs
      resources:
        requests:
          storage: 50Gi # after increasing size: xfs_growfs /dev/sdb
