apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-by
  namespace: $NAMESPACE
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: tech-by
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 20
  template:
    metadata:
      name: tech-by
      labels:
        app: tech-by
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: standard
      containers:
        - name: tech-by$TIMESTAMP
          image: registry.digitalocean.com/tech-by/tech-by:$TAG
          # resources:
          #   requests:
          #     memory: '$TECH_BY_MEMORY_REQUEST'
          #     cpu: '$TECH_BY_CPU_REQUEST'
          env:
            - name: TECH_BY_PORT
              value: '8080'

            - name: FIREBASE_API_KEY
              value: '$FUNDRAISE_FIREBASE_API_KEY'
            - name: FIREBASE_AUTH_DOMAIN
              value: 'fundraise-demo.firebaseapp.com' # FIXME
            - name: FIREBASE_DATABASE_URL
              value: 'https://fundraise-demo.firebaseio.com' # FIXME
            - name: FIREBASE_PROJECT_ID
              value: 'fundraise-demo' # FIXME
            - name: FIREBASE_MESSAGING_SENDER_ID
              value: '228929433695' # FIXME
            - name: TECH_BY_HOST
              value: '$TECH_BY_HOST'
            - name: PUBLIC_PHIL_API_URL
              value: '$PUBLIC_PHIL_API_URL'
            - name: PHIL_API_URL
              value: '$PHIL_API_URL'
            - name: DEV_USE_HTTPS
              value: '0'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 180
