apiVersion: v1
kind: Service
metadata:
  labels:
    app: altelasticsearch
  name: altelasticsearch
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: serving
  - port: 9300
    name: node-to-node
  selector:
    app: altelasticsearch
