apiVersion: v1
kind: Service
metadata:
  name: irs-990-server
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: irs-990-server
      port: 8080
  selector:
    app: irs-990-server
