apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/130
  # loadBalancerIP: '104.248.111.50'
  ports:
    - port: 80
  selector:
    app: load-balancer
  # externalIPs:
  #   - '35.230.40.73'
  sessionAffinity: ClientIP
